Feature/#38 mypage view
U-is-Ni-in-Korea/Android-United pull request #46
Opened 2023-07-16 03:49 UTC by l2zh

## 📌 관련 이슈
- #38 
## 📷 screenshot
https://github.com/U-is-Ni-in-Korea/Android-United/assets/113578158/1a7695d5-1d5c-4fde-921f-603849043be3

## 📝 Work Desciption
- 마이페이지 뷰 그리기
- 마이페이지 기능 구현
- 다이얼로그 크기 수정

## 📚 Reference 혹은 궁금한 사항들
다이얼로그 크기 수정한거 괜찮나 한번씩 봐주세요!

2023-07-16 09:50 UTC, taeheeL requested changes
리뷰 반영해서 다시 푸쉬 부탁드립니다. 최고최고

2023-07-16 09:50 UTC, taeheeL commented on app/src/main/AndroidManifest.xml
> +            android:screenOrientation="portrait"/>
SplashActivity가 맨 위로 오게 이 세 액티비는 맨 아래로 내려주세요!

2023-07-16 09:50 UTC, taeheeL commented on app/src/main/AndroidManifest.xml
> +            android:exported="true"
false!

2023-07-16 09:50 UTC, taeheeL commented on app/src/main/java/sopt/uni/presentation/history/HistoryMainActivity.kt
>          binding.rvHistoryList.adapter = historyAdapter
onCreate 안의 코드들을 함수화해주세요!

2023-07-16 09:50 UTC, taeheeL commented on app/src/main/java/sopt/uni/presentation/history/HistoryMainActivity.kt
> +            startActivity<HomeActivity>()
확장함수 사용 굳!

2023-07-16 09:50 UTC, taeheeL commented on app/src/main/java/sopt/uni/presentation/history/HistorySubActivity.kt
> +        binding.historySubBack.setOnSingleClickListener {
굳

2023-07-16 09:50 UTC, taeheeL commented on app/src/main/java/sopt/uni/presentation/mypage/DatePickerDialogListener.kt
> +}
좋은데요?

2023-07-16 09:50 UTC, taeheeL commented on app/src/main/java/sopt/uni/presentation/mypage/MypageAccountActivity.kt
> +    override fun onCreate(savedInstanceState: Bundle?) {
함수화!

2023-07-16 09:50 UTC, taeheeL commented on app/src/main/java/sopt/uni/presentation/mypage/MypageAccountDialogFragment.kt
> +            dialogTitle.setText("로그아웃 하시겠습니까?")
스트링 추출!

2023-07-16 09:50 UTC, taeheeL commented on app/src/main/java/sopt/uni/presentation/mypage/MypageDatePickerDialogFragment.kt
> +                "일"
month + 1 은 왜하는건가요?

2023-07-16 09:50 UTC, taeheeL commented on app/src/main/java/sopt/uni/presentation/mypage/MypageProfilEditActivity.kt
> +            if (length >= MAX_LENGTH || length == 0) {
상수화 굳굳

2023-07-16 09:50 UTC, taeheeL commented on app/src/main/java/sopt/uni/presentation/mypage/MypageProfilEditActivity.kt
> +    override fun dispatchTouchEvent(event: MotionEvent?): Boolean {
이 함수의 기능과 사용 루트를 설명해주세요!

2023-07-16 09:50 UTC, taeheeL commented on app/src/main/java/sopt/uni/util/binding/BindingDialogFragment.kt
> +abstract class BindingDialogFragment<B : ViewDataBinding>(
굳!

2023-07-17 05:05 UTC, l2zh commented on app/src/main/java/sopt/uni/presentation/mypage/MypageDatePickerDialogFragment.kt
> +                "일"
Android DatePicker의 month 필드가 0부터 11까지라 1을 더해주었습니당!

2023-07-17 05:18 UTC, l2zh commented on app/src/main/java/sopt/uni/presentation/mypage/MypageProfilEditActivity.kt
> +    override fun dispatchTouchEvent(event: MotionEvent?): Boolean {
터치 이벤트가 발생할때 실행되고, 선택한 영역이 edittext 밖일 때 키보드가 닫히고, edittext 맞추어져있던 포커스를 해제 합니다!

2023-07-17 07:24 UTC, taeheeL approved these changes

2023-07-17 07:42 UTC, merged